# Generated by Django 3.2 on 2022-06-29 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_booking', models.DateField(auto_now_add=True)),
                ('end_booking', models.DateField()),
                ('days', models.IntegerField()),
                ('total', models.CharField(max_length=30)),
                ('open', models.BooleanField(default=False)),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residences.residence')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='list_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.booking'),
        ),
    ]
