# Generated by Django 3.2 on 2022-06-30 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0002_auto_20220629_1923'),
        ('accounts', '0002_auto_20220629_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='residence',
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='residences.room'),
        ),
    ]
