# Generated by Django 3.2 on 2022-06-30 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220630_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_booking', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='user',
            name='list_booking',
        ),
        migrations.AddField(
            model_name='user',
            name='list_booking',
            field=models.ManyToManyField(related_name='booking_user_list', to='accounts.Booking'),
        ),
    ]
