# Generated by Django 3.2 on 2022-06-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_booking_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='list_booking',
            field=models.ManyToManyField(blank=True, related_name='booking_user_list', to='accounts.Booking'),
        ),
    ]
