# Generated by Django 3.2 on 2022-06-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_list_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_booking',
            field=models.DateField(auto_now_add=True),
        ),
    ]
