# Generated by Django 3.2 on 2022-06-29 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=500)),
                ('room_quantity', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('Hotel', 'Hotel'), ('Cabin', 'Read')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decription', models.TextField()),
                ('room_id', models.CharField(max_length=10)),
                ('room_bed', models.CharField(choices=[('Single Bed', 'Single'), ('Double Bed', 'Double'), ('Couple Bed', 'Couple')], max_length=10)),
                ('daily_price', models.CharField(max_length=10)),
                ('vip', models.BooleanField(default=False)),
                ('extra_price', models.CharField(blank=True, max_length=10, null=True)),
                ('residence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room_from_residence', to='residences.residence')),
            ],
        ),
        migrations.AddField(
            model_name='residence',
            name='rooms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rooms_in_residence', to='residences.room'),
        ),
    ]
