# Generated by Django 3.2 on 2022-06-29 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residence',
            name='rooms',
        ),
        migrations.AddField(
            model_name='residence',
            name='rooms',
            field=models.ManyToManyField(related_name='rooms_in_residence', to='residences.Room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_from_residence', to='residences.residence'),
        ),
    ]
