# Generated by Django 3.2 on 2022-06-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0002_auto_20220629_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='daily_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='extra_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
