# Generated by Django 3.2 on 2022-07-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0003_auto_20220630_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='description',
            field=models.TextField(default='default description, you should edit this', max_length=300),
        ),
        migrations.AddField(
            model_name='residence',
            name='main_picture',
            field=models.ImageField(default='residences/default.svg', upload_to='residences/'),
        ),
    ]
